import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header.component";
import AmplifyContext from "@/context/amplify.context";
import AuthDetailsContextProvider from "@/context/auth.context";
import { getAuthenticatedUser } from "@/utils/server.utils";
import "@aws-amplify/ui-react/styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const authDetails = await getAuthenticatedUser();
  return (
    <html lang="en">
      <AmplifyContext>
        <AuthDetailsContextProvider details={authDetails}>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <Header />
            {children}
          </body>
        </AuthDetailsContextProvider>
      </AmplifyContext>
    </html>
  );
}
